# tasks/main.yml
---

- name: Install latest openshift client 
  pip:
    name: https://github.com/openshift/openshift-restclient-python/archive/master.tar.gz
    state: latest 
    virtualenv: "{{ virtualenv }}"
  when: install_python_requirements

